### ISSUE TITLE
i having error after launch with MaxLauncher.bat 

### ISSUE THREAD

**Issue by tws0002** [gtvfx/mxs_bundle#1]
Here is the error 

|=============== Loading Scripted Plugins ===============|
|==================== ILM Max Starup ====================|
|=============== Loading Startup Scripts ===============|
Loading File: GTVFX-00_callbacksStartUp
-- Error occurred in anonymous codeblock; filename: K:\SES\Library\mxs_bundle\lib\startup\GTVFX-00_callbacksStartUp.ms; position: 112; line: 1
-- MAXScript Auto-load Script Error - C:\Users\Des-PC\AppData\Local\Autodesk\3dsMax\2018 - 64bit\ENU\scripts\startup\mxs_init.ms Exception:
-- Unable to convert: undefined to type: FileName
-- MAXScript callstack:
--	thread data: threadID:3668
--	------------------------------------------------------
--	[stack level: 0]
--	In i loop; filename: K:\SES\Library\mxs_bundle\lib\startup\GTVFX-00_callbacksStartUp.ms; position: 113; line: 1
--		Parameters:
--			i: "K:\SES\Library\mxs_bundle\lib\startup\GTVFX-00_callbacksStartUp.ms"
--		Locals:
--			i: "K:\SES\Library\mxs_bundle\lib\startup\GTVFX-00_callbacksStartUp.ms"
--		Externals:
--			owner: undefined
--	------------------------------------------------------
--	[stack level: 1]
--	called from LoadFilesFromDir(); filename: K:\SES\Library\mxs_bundle\lib\mxsLibMaxStartup.ms; position: 891; line: 39
--	member of: StructDef:DefaultInit
--		Parameters:
--			dir: "K:\SES\Library\mxs_bundle\lib\startup"
--			fileType: ".ms*"
--		Locals:
--			dir: "K:\SES\Library\mxs_bundle\lib\startup"
--			fileType: ".ms*"
--			fileArr: #("K:\SES\Library\mxs_bundle\lib\startup\GTVFX-00_callbacksStartUp.ms", "K:\SES\Library\mxs_bundle\lib\startup\GTVFX-01_toolboxStartUp.ms", "K:\SES\Library\mxs_bundle\lib\startup\GTVFX-02_menuStartUp.ms", "K:\SES\Library\mxs_bundle\lib\startup\GTVFX-LIB_layIsoStartUp.ms", "K:\SES\Library\mxs_bundle\lib\startup\toolbox_init.ms")
--		Externals:
--			owner: (DefaultInit init:true)
--	------------------------------------------------------
--	[stack level: 2]
--	called from LoadFilesFromDir(); filename: K:\SES\Library\mxs_bundle\lib\mxsLibMaxStartup.ms; position: 1721; line: 81
--	member of: StructDef:WorkstationInit
--		Parameters:
--			dir: "K:\SES\Library\mxs_bundle\lib\startup"
--			fileType: ".ms*"
--		Locals:
--			dir: "K:\SES\Library\mxs_bundle\lib\startup"
--			fileType: ".ms*"
--		Externals:
--			_defInit: Struct member:_defInit : (DefaultInit init:true)
--			owner: (WorkstationInit _defInit:(DefaultInit init:true) _tabInit:true init:<<member value not evaluated yet>>)
--	------------------------------------------------------
--	[stack level: 3]
--	called from LoadStartupLibs(); filename: K:\SES\Library\mxs_bundle\lib\mxsLibMaxStartup.ms; position: 2415; line: 114
--	member of: StructDef:WorkstationInit
--		Locals:
--			startupDir: "K:\SES\Library\mxs_bundle\lib\startup"
--		Externals:
--			owner: (WorkstationInit _defInit:(DefaultInit init:true) _tabInit:true init:<<member value not evaluated yet>>)
--			this: Struct member:this : (WorkstationInit _defInit:(DefaultInit init:true) _tabInit:true init:<<member value not evaluated yet>>)
--	------------------------------------------------------
--	[stack level: 4]
--	called from _init(); filename: K:\SES\Library\mxs_bundle\lib\mxsLibMaxStartup.ms; position: 3111; line: 150
--	member of: StructDef:WorkstationInit
--		Locals:
--		Externals:
--			owner: (WorkstationInit _defInit:(DefaultInit init:true) _tabInit:true init:<<member value not evaluated yet>>)
--			this: Struct member:this : (WorkstationInit _defInit:(DefaultInit init:true) _tabInit:true init:<<member value not evaluated yet>>)
--	------------------------------------------------------
--	[stack level: 5]
--	called from anonymous codeblock; filename: K:\SES\Library\mxs_bundle\lib\mxsLibMaxStartup.ms; position: 3520; line: 161
--		Locals:
--		Externals:
--			WorkstationInit: Global:WorkstationInit : StructDef:WorkstationInit
--	------------------------------------------------------
--	[stack level: 6]
--	called from anonymous codeblock; filename: K:\SES\Library\mxs_bundle\lib\mxsLibMaxStartup.ms; position: 3605; line: 174
--		Locals:
--			startupLib: "K:\SES\Library\mxs_bundle\lib\mxsLibMaxStartup.ms"
--			sysenv: dotNetClass:System.Environment
--		Externals:
--	------------------------------------------------------
--	[stack level: 7]l--	called from top-level

please help 
Desmond

**Comment by gtvfx** [comment]
Hey Desmond,

I'll have a look at this over the weekend. Which version of 3dsmax are you using?

**Comment by tws0002** [comment]
Thanks for the quick reply. 

I try 2015,2016 and 2018 but all have the same error!! 

Thanks 
Desmond

**Comment by gtvfx** [comment]
Hey Desmond,

I've just pushed a new update. This update just removes some files from the startup routine that were trying to source other files from deprecated paths. These files were initializing the toolbox scripts, so you won't be getting that until I can re-implement the code for this bundle.

So all that you'll be getting right now is the module management and the existing libs. I'll be working on documentation and probably do some videos on how to use all of this, but feel free to send questions.

Best,
Gavyn

**Comment by tws0002** [comment]
Thanks Gavyn for the quick fix. Will try it when back in studion.

Thanks 
Desmond

**Comment by gtvfx** [comment]
I've gone ahead and pushed out another update that adds in the code for the GTVFX Toolbox. So you'll get the "GTVFX_Toolbox" system menu with it's accompanying tools and the main Toolbox UI as well.

I cleaned out the TabMenu a great deal to remove placeholder tools that weren't working so that now it's just more of a reference for use.
